#######################################################################################################################
"""
Static data for dog breeds in backend.

Defines the DOG_BREEDS tuple and the ensure_dog_breeds utility for populating the database with standard breeds.
"""

#######################################################################################################################
# Imports
#######################################################################################################################

from sqlmodel import select

from database.core.models import BreedDbModel, Species

#######################################################################################################################
# Globals
#######################################################################################################################

DOG_BREEDS = (
    "Affenpinscher",
    "Afghan Hound",
    "Aidi",
    "Airedale Terrier",
    "Akbash",
    "Akita",
    "Alano Espanol",
    "Alaskan husky",
    "Alaskan Klee Kai",
    "Alaskan Malamute",
    "Alpine Dachsbracke",
    "American Bulldog",
    "American Bully",
    "American Cocker Spaniel",
    "American English Coonhound",
    "American Eskimo Dog",
    "American Foxhound",
    "American Hairless Terrier",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd Dog",
    "Andalusian Hound",
    "Anglo-Francais de Petite Venerie",
    "Appenzeller Sennenhund",
    "Ariegeois",
    "Armant",
    "Armenian Gampr dog",
    "Artois Hound",
    "Australian Cattle Dog",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Stumpy Tail Cattle Dog",
    "Australian Terrier",
    "Austrian Black and Tan Hound",
    "Austrian Pinscher",
    "Azawakh",
    "Bakharwal dog",
    "Banjara Hound",
    "Barbado da Terceira",
    "Barbet",
    "Basenji",
    "Basque Shepherd Dog",
    "Basset Artesien Normand",
    "Basset Bleu de Gascogne",
    "Basset Fauve de Bretagne",
    "Basset Hound",
    "Bavarian Mountain Hound",
    "Beagle",
    "Beagle-Harrier",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Bergamasco Shepherd",
    "Berger Picard",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Billy",
    "Black and Tan Coonhound",
    "Black and Tan Virginia Foxhound",
    "Black Mouth Cur",
    "Black Norwegian Elkhound",
    "Black Russian Terrier",
    "Bloodhound",
    "Blue Lacy",
    "Blue Picardy Spaniel",
    "Bluetick Coonhound",
    "Boerboel",
    "Bohemian Shepherd",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Bosnian Coarse-haired Hound",
    "Boston Terrier",
    "Bouvier des Ardennes",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Bracco Italiano",
    "Braque d'Auver",
    "Braque de l'Ari",
    "Braque du Bourbonnais",
    "Braque Francais",
    "Braque Saint-Germain",
    "Briard",
    "Briquet Griffon Vendeen",
    "Brittany",
    "Broholmer",
    "Bruno Jura Hound",
    "Brussels Griffon",
    "Bucovina Shepherd Dog",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Bully Kutta",
    "Burgos Pointer",
    "Cairn Terrier",
    "Campeiro Bulldog",
    "Canaan Dog",
    "Canadian Eskimo Dog",
    "Cane Corso",
    "Cantabrian Water Dog",
    "Cao da Serra de Aires",
    "Cao de Castro Laboreiro",
    "Cao de Gado Transmontano",
    "Cao Fila de Sao Miguel",
    "Cardigan Welsh Corgi",
    "Carolina Dog",
    "Carpathian Shepherd Dog",
    "Catahoula Leopard Dog",
    "Catalan Sheepdog",
    "Caucasian Shepherd Dog",
    "Cavalier King Charles Spaniel",
    "Central Asian Shepherd Dog",
    "Cesky Fousek",
    "Cesky Terrier",
    "Chesapeake Bay Retriever",
    "Chien Francais Blanc et Noir",
    "Chien Francais Blanc et Orange",
    "Chien Francais Tricolore",
    "Chihuahua",
    "Chilean Terrier",
    "Chinese Chongqing Dog",
    "Chinese Crested Dog",
    "Chinook",
    "Chippiparai",
    "Chow Chow",
    "Cimarran Uruguayo",
    "Cirneco dell'E",
    "Clumber Spaniel",
    "Cocker Spaniel",
    "Colombian fino hound",
    "Combai",
    "Coton de Tulear",
    "Cretan Hound",
    "Croatian Sheepdog",
    "Cross breed",
    "Curly-Coated Retriever",
    "Cursinu",
    "Czechoslovakian Wolfdog",
    "Dachshund",
    "Dalmatian",
    "Dandie Dinmont Terrier",
    "Danish-Swedish Farmdog",
    "Doberman Pinscher",
    "Dogo Argentino",
    "Dogo Guatemalteco",
    "Dogue Brasileiro",
    "Dogue de Bordeaux",
    "Drentse Patrijshond",
    "Drever",
    "Dunker",
    "Dutch Shepherd",
    "Dutch Smoushond",
    "East European Shepherd",
    "East Siberian Laika",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Mastiff",
    "English Setter",
    "English Shepherd",
    "English Springer Spaniel",
    "English Toy Terrier",
    "Entlebucher Mountain Dog",
    "Estonian Hound",
    "Estrela Mountain Dog",
    "Eurasier",
    "Field Spaniel",
    "Fila Brasileiro",
    "Fila da Terceira",
    "Finnish Hound",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "French Bulldog",
    "French Spaniel",
    "Galgo Espanol",
    "Galician Shepherd Dog",
    "Garafian Shepherd",
    "Gascon Saintongeois",
    "Georgian Shepherd",
    "German Hound",
    "German Longhaired Pointer",
    "German Pinscher",
    "German Roughhaired Pointer",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Spaniel",
    "German Spitz",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Go?czy Polski",
    "Golden Retriever",
    "Gordon Setter",
    "Gran Mastan de Borinquen",
    "Grand Anglo-Francais Blanc et Noir",
    "Grand Anglo-Francais Blanc et Orange",
    "Grand Anglo-Francais Tricolore",
    "Grand Basset Griffon Vendeen",
    "Grand Bleu de Gascogne",
    "Grand Griffon Vendeen",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greek Harehound",
    "Greek Shepherd",
    "Greenland Dog",
    "Greyhound",
    "Griffon Bleu de Gascogne",
    "Griffon Fauve de Bretagne",
    "Griffon Nivernais",
    "Groenendael",
    "Gull Terrier",
    "Hamiltonstavare",
    "Hanover Hound",
    "Harrier",
    "Havanese",
    "Himalayan Sheepdog",
    "Hokkaido",
    "Hortaya borzaya",
    "Hovawart",
    "Huntaway",
    "Hygen Hound",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Indian pariah dog",
    "Indian Spitz",
    "Irish Red and White Setter",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Istrian Coarse-haired Hound",
    "Istrian Shorthaired Hound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Jagdterrier",
    "Japanese Chin",
    "Japanese Spitz",
    "Japanese Terrier",
    "Jindo",
    "Jonangi",
    "Kai Ken",
    "Kangal Shepherd Dog",
    "Kanni",
    "Karakachan dog",
    "Karelian Bear Dog",
    "Karst Shepherd",
    "Keeshond",
    "Kerry Beagle",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "King Shepherd",
    "Kintamani",
    "Kishu",
    "Komondor",
    "Kooikerhondje",
    "Koolie",
    "Koyun dog",
    "Kromfohrlander",
    "Kuchi",
    "Kumaon Mastiff",
    "Kunming wolfdog",
    "Kuvasz",
    "Labrador Retriever",
    "Laekenois",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Landseer",
    "Lapponian Herder",
    "Lapponian Shepherd",
    "Large Munsterlunder",
    "Leonberger",
    "Lhasa Apso",
    "Lithuanian Hound",
    "Lowchen",
    "Lupo Italiano",
    "Mackenzie River husky",
    "Magyar agar",
    "Mahratta Greyhound",
    "Malinois",
    "Maltese",
    "Manchester Terrier",
    "Maremma Sheepdog",
    "McNab dog",
    "Miniature American Shepherd",
    "Miniature Bull Terrier",
    "Miniature Dachshund",
    "Miniature Fox Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Miniature Shar Pei",
    "Montenegrin Mountain Hound",
    "Moscow Water Dog",
    "Mountain Cur",
    "Mucuchies",
    "Mudhol Hound",
    "Mudi",
    "Neapolitan Mastiff",
    "New Zealand Heading Dog",
    "Newfoundland",
    "Norfolk Terrier",
    "Norrbottenspets",
    "Northern Inuit Dog",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old Croatian Sighthound",
    "Old Danish Pointer",
    "Old English Sheepdog",
    "Old English Terrier",
    "Olde English Bulldogge",
    "Original Fila Brasileiro",
    "Other",
    "Otterhound",
    "Pachon Navarro",
    "Paisley Terrier",
    "Pandikona",
    "Papillon",
    "Parson Russell Terrier",
    "Pastore della Lessinia e del Lag",
    "Patagonian Sheepdog",
    "Patterdale Terrier",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Perro de Pastor Mallorquin",
    "Perro de Presa Canario",
    "Perro de Presa Mallorquin",
    "Peruvian Inca Orchid",
    "Petit Basset Griffon Vendeen",
    "Petit Bleu de Gascogne",
    "Phalene",
    "Pharaoh Hound",
    "Phu Quoc Ridgeback",
    "Picardy Spaniel",
    "Plott Hound",
    "Plummer Terrier",
    "Podenco Canario",
    "Pointer",
    "Poitevin",
    "Polish Greyhound",
    "Polish Hound",
    "Polish Lowland Sheepdog",
    "Polish Tatra Sheepdog",
    "Pomeranian",
    "Pont-Audemer Spaniel",
    "Poodle",
    "Porcelaine",
    "Portuguese Podengo",
    "Portuguese Pointer",
    "Portuguese Water Dog",
    "Posavac Hound",
    "Potsdam Greyhound",
    "Prazsky Krysarik",
    "Pudelpointer",
    "Pug",
    "Puli",
    "Pumi",
    "Pungsan dog",
    "Pyrenean Mastiff",
    "Pyrenean Shepherd",
    "Rafeiro do Alentejo",
    "Rajapalayam",
    "Rampur Greyhound",
    "Rastreador Brasileiro",
    "Rat Terrier",
    "Ratonero Bodeguero Andaluz",
    "Ratonero Mallorquin",
    "Ratonero Murciano de Huerta",
    "Ratonero Valenciano",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Romanian Mioritic Shepherd Dog",
    "Romanian Raven Shepherd Dog",
    "Rottweiler",
    "Rough Collie",
    "Russell Terrier",
    "Russian Spaniel",
    "Russian Toy",
    "Russo-European Laika",
    "Saarloos Wolfdog",
    "Sabueso Espanol",
    "Saint Bernard",
    "Saint-Usuge Spaniel",
    "Saluki",
    "Samoyed",
    "Sapsali",
    "Sarplaninac",
    "Schapendoes",
    "Schillerstovare",
    "Schipperke",
    "Schweizer Laufhund",
    "Schweizerischer Niederlaufhund",
    "Scotch Collie",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Segugio Italiano",
    "Seppala Siberian Sleddog",
    "Serbian Hound",
    "Serbian Tricolour Hound",
    "Serrano Bulldog",
    "Shar Pei",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Shikoku",
    "Shiloh Shepherd",
    "Siberian Husky",
    "Silken Windhound",
    "Silky Terrier",
    "Sinhala Hound",
    "Skye Terrier",
    "Sloughi",
    "Slovakian Wirehaired Pointer",
    "Slovenski cuvac",
    "Slovenski kopov",
    "Smalandsstovare",
    "Small Greek domestic dog",
    "Small Munsterlunder",
    "Smooth Collie",
    "Smooth Fox Terrier",
    "Soft-Coated Wheaten Terrier",
    "South Russian Ovcharka",
    "Spanish Mastiff",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Sporting Lucas Terrier",
    "Springer Spaniel",
    "Stabyhoun",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Stephens Cur",
    "Styrian Coarse-haired Hound",
    "Sussex Spaniel",
    "Swedish Elkhound",
    "Swedish Lapphund",
    "Swedish Vallhund",
    "Tahltan Bear Dog",
    "Taigan",
    "Taiwan Dog",
    "Tamaskan Dog",
    "Teddy Roosevelt Terrier",
    "Telomian",
    "Tenterfield Terrier",
    "Terrier Brasileiro",
    "Tervuren",
    "Thai Bangkaew Dog",
    "Thai Ridgeback",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Tornjak",
    "Tosa",
    "Toy Fox Terrier",
    "Toy Manchester Terrier",
    "Transylvanian Hound",
    "Treeing Cur",
    "Treeing Tennessee Brindle",
    "Treeing Walker Coonhound",
    "Trigg Hound",
    "Tyrolean Hound",
    "Unknown",
    "Villano de Las Encartaciones",
    "Villanuco de Las Encartaciones",
    "Vizsla",
    "Volpino Italiano",
    "Weimaraner",
    "Welsh Sheepdog",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "West Highland White Terrier",
    "West Siberian Laika",
    "Westphalian Dachsbracke",
    "Wetterhoun",
    "Whippet",
    "White Shepherd",
    "White Swiss Shepherd Dog",
    "Wire Fox Terrier",
    "Wirehaired Pointing Griffon",
    "Wirehaired Vizsla",
    "Xiasi Dog",
    "Xoloitzcuintli",
    "Yakutian Laika",
    "Yorkshire Terrier",
)

#######################################################################################################################
# Body
#######################################################################################################################


def ensure_dog_breeds(session):
    """Ensure all standard dog breeds exist in the database for the Canine species."""
    existing = set(
        name for name in session.exec(select(BreedDbModel.name).where(BreedDbModel.species == Species.CANINE)).all()
    )
    to_add = [BreedDbModel(name=dog, species=Species.CANINE) for dog in DOG_BREEDS if dog not in existing]
    if to_add:
        session.add_all(to_add)
        session.commit()


#######################################################################################################################
# End of file
#######################################################################################################################
