"""
init.

Revision ID: 5d4dd26e0f8d
Revises:
Create Date: 2026-02-06 10:48:23.841149

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d4dd26e0f8d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("species", sa.Enum("CANINE", "FELINE", "EQUINE", name="species"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_breed_id"), "breed", ["id"], unique=False)
    op.create_index(op.f("ix_breed_name"), "breed", ["name"], unique=False)
    op.create_index(op.f("ix_breed_species"), "breed", ["species"], unique=False)
    op.create_table(
        "case",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("practice_animal_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("chip_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "sex", sa.Enum("MALE", "MALE_NEUTERED", "FEMALE", "FEMALE_NEUTERED", "UNKNOWN", name="sex"), nullable=False
        ),
        sa.Column("birth_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("create_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("breed_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["breed_id"],
            ["breed.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_case_id"), "case", ["id"], unique=False)
    op.create_index(op.f("ix_case_name"), "case", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_case_name"), table_name="case")
    op.drop_index(op.f("ix_case_id"), table_name="case")
    op.drop_table("case")
    op.drop_index(op.f("ix_breed_species"), table_name="breed")
    op.drop_index(op.f("ix_breed_name"), table_name="breed")
    op.drop_index(op.f("ix_breed_id"), table_name="breed")
    op.drop_table("breed")
    # ### end Alembic commands ###
